//----------------------------------------------------
// The following code is a manually-created simulation
// of the symbol code generated by CUP
//
// NOTE TO STUDENTS: You will need to add any new
// symbols you require for the Lexer into this file!
//----------------------------------------------------

public class sym {
  /* terminals */
  public static final int EOF = 1;
  public static final int PLUS = 2;
  public static final int NUM = 3;
  public static final int QSTRING = 4;
  public static final int ID = 5;
  public static final int ASSIGN = 6;
  public static final int NUMTYPE = 7;
  public static final int SEMICOL = 8;
  public static final int PRINT = 9;
  public static final int TEXT = 10;
  public static final int BOOL = 11;
  public static final int OR = 12;
  public static final int AND = 13;
  public static final int TRUE = 14;
  public static final int FALSE = 15;
  public static final int NOT = 16;
  public static final int LT = 17;
  public static final int GT = 18;
  public static final int OPCURLY = 19;
  public static final int CLCURLY = 20;
  public static final int COMMA = 21;
  public static final int LIST = 22;
  public static final int READ = 23;
  public static final int ERROR = 24;
  public static final int EXIT = 25;
  public static final int FUNC = 26;
  public static final int VOID = 27;
  public static final int OPPAREN = 28;
  public static final int CLPAREN = 29;
  public static final int INPUT = 30;
  public static final int UNTIL = 31;
  public static final int DIVIDE = 32;
  public static final int OPSQUARE = 33;
  public static final int CLSQUARE = 34;
  public static final int OPFILTER = 35;
  public static final int CLFILTER = 36;
  public static final int WRITE = 37;
  public static final int IF = 38;
  public static final int ELSE = 39;
  public static final int EQUALS = 40;
  public static final int COLON = 41;
  public static final int FOR = 42;
  public static final int RETURN = 43;
  public static final int SWITCH = 44;
  public static final int CASE = 45;
  public static final int DEFAULT = 46;
  public static final int FILEAPP = 47;
  public static final int LESSEQUAL = 48;
  public static final int GREATEQUAL = 49;
  public static final int MINUS = 50;
  public static final int TIMES = 51;
  public static final int MOD = 52;
}

